# Web Search Agent
search_engine: "google" # "bing"
search_top_k: 3
search_region: "us"
search_lang: "en"
page_view_port_size: 1024*40
# serper_api_key: "key here if you use serper"

# base_url: "https://openrouter.ai/api/v1"
# api_key: "sk-or-v1-"
reading_agent_model: "qwen/qwen-plus"
quick_summary_model: "qwen/qwen-plus"

azure_bing_search_subscription_key: "key here if you use azure bing"
azure_bing_search_mkt: "zh-CN" # "en-US"

query_save_path: "./scrl/handler/cache/search_result.json"

server_url_list:
  - "http://localhost:5000"
